In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
y = torch.arange(12)
y.reshape(3,-1) # second argument can be inferred from first as 12/3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
y = torch.arange(12)
y.reshape(-1,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.randn(3,4) # creates a tensor with elements drawn from
                 # a standard Gaussian (normal) distribution with mean 0 and standard deviation 1

tensor([[ 0.7433, -1.5750, -0.6988,  0.6793],
        [-0.5405, -1.4745, -0.3137,  0.2861],
        [ 0.9445,  0.5806,  1.1881,  2.3407]])

In [12]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [14]:
X[1,2] = 17
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 17,  7],
        [ 8,  9, 10, 11]])

In [15]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [16]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [17]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([2,2,2,2])

x+y, x-y, x*y, x/y, x**y

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1,  4,  9, 16]))

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[0,2,3,4], [2,3,4,5], [1,4,6,8]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  2.,  3.,  4.],
         [ 2.,  3.,  4.,  5.],
         [ 1.,  4.,  6.,  8.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  5.],
         [ 8.,  9., 10., 11.,  1.,  4.,  6.,  8.]]))

In [19]:
X==Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

In [21]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])